pipeline {

    agent any

    tools {
        maven 'Maven3'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('app/springboot-app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('app/springboot-app') {
                    sh 'mvn test'
                }
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'app/springboot-app/target/*.jar'
        }
    }
}